### Login as admin WITHOUT 2FA (treated as normal user)
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "email": "marta.rossi@example.com",
  "password": "sunshine123"
}

###

### Login as admin WITH 2FA (full admin access)
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "email": "marta.rossi@example.com",
  "password": "sunshine123",
  "otp": "729736"  
}

###

### Get current logged in user
GET http://localhost:3001/api/sessions/current

###

### Logout user
DELETE http://localhost:3001/api/sessions/current

###

### Get all posts
GET http://localhost:3001/api/posts

###

### Get a single post (replace :id with actual post ID)
GET http://localhost:3001/api/posts/1

###

### Add a new post
POST http://localhost:3001/api/posts
Content-Type: application/json

{
  "title": "My first post",
  "text": "Hello everyone, this is my first post!",
  "maxComments": 5
}

###

### Delete own post (replace :id with actual post ID)
DELETE http://localhost:3001/api/posts/1

###

### Delete ANY post as ADMIN (replace :id with actual post ID)
DELETE http://localhost:3001/api/admin/posts/1

###

### Get comments for a post (requires login) (replace :id)
GET http://localhost:3001/api/posts/4/comments

###

### Add a comment to a post (replace :id with actual post ID)
POST http://localhost:3001/api/posts/1/comments
Content-Type: application/json

{
  "text": "This is a comment!"
}

###

### Edit own comment (replace :id with actual comment ID)
PUT http://localhost:3001/api/comments/1
Content-Type: application/json

{
  "text": "Edited comment text"
}

###

###
GET  http://localhost:3001/api/posts/1/comments/count



### Edit ANY comment as ADMIN (replace :id with actual comment ID)
PUT http://localhost:3001/api/admin/comments/1
Content-Type: application/json

{
  "text": "Admin updated this comment."
}

###

### Delete own comment (replace :id)
DELETE http://localhost:3001/api/comments/1

###

### Delete ANY comment as ADMIN (replace :id)
DELETE http://localhost:3001/api/admin/comments/1

###

### Add \"interesting\" flag to a comment (replace :id)
POST http://localhost:3001/api/comments/1/flag

###

### Remove \"interesting\" flag (replace :id)
DELETE http://localhost:3001/api/comments/1/flag

###

### Get all \"interesting\" flags for logged user
GET http://localhost:3001/api/users/me/flags
